Propagate push workflow to pr; remove debug; fixing osx

diff --git a/.github/workflows/pr_master_test.yml b/.github/workflows/pr_master_test.yml
--- a/.github/workflows/pr_master_test.yml
+++ b/.github/workflows/pr_master_test.yml
@@ -22,7 +22,7 @@ env:
   CACHE_VER: v1
 
 jobs:
-  pyomo-tests:
+  build:
     name: ${{ matrix.TARGET }}/${{ matrix.python }}${{ matrix.NAME }}
     runs-on: ${{ matrix.os }}
     strategy:
@@ -63,6 +63,11 @@ jobs:
 
     steps:
     - uses: actions/checkout@v2
+
+    - name: Configure job parameters
+      run: |
+        JOB="${{matrix.TARGET}}/${{matrix.python}}${{matrix.NAME}}"
+        echo "::set-env name=GHA_JOBNAME::"`echo "$JOB" | sed 's|/|_|g'`
 
     # Ideally we would cache the conda downloads; however, each cache is
     # over 850MB, and with 5 python versions, that would consume 4.2 of
@@ -442,11 +447,44 @@ jobs:
             echo "Uploading coverage to codecov (attempt ${i})"
             bash $CODECOV -Z -X gcov -X s3 -f coverage.xml
             if test $? == 0; then
+                echo "PASS" > ${GITHUB_WORKSPACE}/codecov.result
                 break
-            elif test $i -ge 5; then
-                exit 1
+            elif test $i -ge 2; then
+                # Do not fail the build just because the codecov upload fails
+                echo "FAIL" > ${GITHUB_WORKSPACE}/codecov.result
+                break
             fi
             DELAY=$(( RANDOM % 30 + 30))
             echo "Pausing $DELAY seconds before re-attempting upload"
             sleep $DELAY
         done
+
+    - name: Record build artifacts
+      uses: actions/upload-artifact@v2
+      with:
+        name: ${{github.job_id}}_${{env.GHA_JOBNAME}}
+        path: |
+          codecov.result
+          TEST-pyomo.xml
+
+  post:
+    name: post-build
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download build artifacts
+        uses: actions/download-artifact@v2
+        with:
+          path: artifacts
+
+      - name: Check codecov upload success
+        run: |
+          FAIL=`grep FAIL artifacts/*/codecov.result | wc -l`
+          ALL=`ls -1 artifacts/*/codecov.result | wc -l`
+          # Fail is more than 1/9 codecov uploads fail
+          echo "$FAIL of $ALL codecov uploads failed"
+          if test $(( $FAIL * 9 )) -gt $ALL; then
+              echo "More than 1/9 codecov uploads failed:"
+              grep FAIL artifacts/*/codecov.result
+              exit 1
+          fi
