Add debugging for when conda env setup fails

diff --git a/.github/workflows/test_branches.yml b/.github/workflows/test_branches.yml
--- a/.github/workflows/test_branches.yml
+++ b/.github/workflows/test_branches.yml
@@ -318,7 +318,20 @@ jobs:
             fi
         done
         echo "*** Install Pyomo dependencies ***"
-        conda install --update-deps -q -y $CONDA_DEPENDENCIES
+        conda install --update-deps -q -y $CONDA_DEPENDENCIES || CONDA_INSTALL_ERR=1
+        if test -n "$CONDA_INSTALL_ERR"; then
+            CONDAENV=$(conda list)
+            CONDA_INSTALL_ERR=
+            for PKG in $CONDA_DEPENDENCIES; do
+                if test `echo "$CONDAENV" | grep "^$PKG " | wc -l` -eq 0; then
+                    echo "Conda dependency $PKG failed to install"
+                    CONDA_INSTALL_ERR=1
+                fi
+            done
+            if test -n "$CONDA_INSTALL_ERR"; then
+                exit 1
+            fi
+        fi
         if test -z "${{matrix.slim}}"; then
             PYVER=$(echo "py${{matrix.python}}" | sed 's/\.//g')
             echo "Installing for $PYVER"
@@ -334,7 +347,7 @@ jobs:
                 echo "$_PKGLIST"
                 _BASE=$(echo "$PKG" | sed 's/[=<>].*//')
                 _BUILDS=$(echo "$_PKGLIST" | grep "^$_BASE " \
-                    | sed -r 's/\s+/ /g' | cut -d\  -f3) || echo ""x
+                    | sed -r 's/\s+/ /g' | cut -d\  -f3) || echo ""
                 if test -n "$_BUILDS"; then
                     _ISPY=$(echo "$_BUILDS" | grep "^py") \
                         || echo "No python build detected"
